---
title: "Explore coverage drop around probes"
author: "Jelmer Poelstra"
date: today
format:
  html:
    self-contained: true
    cache: false
    number-sections: true
    number-depth: 2
    toc: true
    fig-dpi: 300
    df-print: kable
    grid:
      body-width: 800px
knitr:
  opts_chunk:
    message: FALSE
    out.width: "85%"
    R.options: 
      knitr.table.html.attr: "quarto-disable-processing=true"
execute: 
  warning: false
editor_options: 
  chunk_output_type: console
---

<br>

-------

```{r}
# Load packages
library(tidyverse)
library(here)

# Settings
cols_dp <- c("chr", "start", "end", "locus", "relpos", "depth")
buffer_size <- 1000 # 1000 bp on each side
theme_set(theme_bw(base_size = 14))
theme_update(
  plot.title = element_text(face = "bold"),
  panel.grid.minor = element_blank()
)

# Define the input files
depth_file <- here("sandbox/depth.tsv")
bed_file <- here("results/blast_probes/probes_no-buffer.bed")

# Read the input files
depth_init <- read_tsv(depth_file, col_names = cols_dp, col_types = "ciicii")
loci_init <- read_tsv(bed_file, col_names = cols_dp[1:4], col_types = "ciic")
```

```{r}
loci <- loci_init |>
  mutate(size = end - start, midpoint = start + (size / 2)) |>
  select(locus, size, midpoint)

depth <- depth_init |>
  mutate(abspos = (start + relpos) - 1, .by = locus) |>
  select(locus, abspos, relpos, depth) |>
  left_join(loci, by = "locus") |>
  mutate(relpos = round(abspos - midpoint))

# 3. Calculate the average depth across all loci at each relative position
avg_largeloci <- depth |>
  filter(size > 1950) |>
  summarize(depth = mean(depth, na.rm = TRUE), .by = relpos)

avg_smallloci <- depth |>
  filter(size < 210 & size > 190 ) |>
  summarize(depth = mean(depth, na.rm = TRUE), .by = relpos)
```

## Small loci

```{r}
avg_smallloci |>
  ggplot(aes(x = relpos, y = depth)) +
  geom_vline(xintercept = 0, color = "black", linewidth = 1) +
  geom_vline(xintercept = -100, linetype = "dashed", color = "red", linewidth = 0.8) +
  geom_vline(xintercept = 100, linetype = "dashed", color = "red", linewidth = 0.8) +
  geom_area(fill = "dodgerblue", color = "dodgerblue4", alpha = 0.4, linewidth = 0.1) +
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.03))) +
  labs(
    title = "Average UCE coverage profile for 200-bp loci",
    subtitle = "Red dashed lines marks the boundaries of the targeted regions",
    x = "Distance from target center (bp)",
    y = "Average depth (X)"
  )
```

## Large loci

```{r}
avg_largeloci |>
  ggplot(aes(x = relpos, y = depth)) +
  geom_vline(xintercept = 0, color = "black", linewidth = 1) +
  geom_vline(xintercept = -1000, linetype = "dashed", color = "red", linewidth = 0.8) +
  geom_vline(xintercept = 1000, linetype = "dashed", color = "red", linewidth = 0.8) +
  geom_area(fill = "dodgerblue", color = "dodgerblue4", alpha = 0.4, linewidth = 0.1) +
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.03))) +
  labs(
    title = "Average UCE coverage profile for 2000-bp loci",
    subtitle = "Red dashed lines marks the boundaries of the targeted regions",
    x = "Distance from target center (bp)",
    y = "Average depth (X)"
  )
```

## Plotting a few individual loci (not the average)

```{r}
depth |>
  filter(locus %in% unique(locus)[1:3]) |> 
  ggplot(aes(x = relpos, y = depth, fill = locus, color = locus)) +
  geom_vline(xintercept = 0, color = "black", linewidth = 1) +
  geom_area(alpha = 0.4) +
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.03))) +
  labs(
    x = "Distance from Target Center (bp)",
    y = "Average Sequencing Depth (X)"
  )
```
