---
title: "Explore number of variants per locus"
author: "Jelmer Poelstra"
date: today
format:
  html:
    self-contained: true
    cache: false
    number-sections: true
    number-depth: 2
    toc: true
    fig-dpi: 300
    df-print: kable
    grid:
      body-width: 800px
knitr:
  opts_chunk:
    message: FALSE
    out.width: "85%"
    R.options: 
      knitr.table.html.attr: "quarto-disable-processing=true"
execute: 
  warning: false
editor_options: 
  chunk_output_type: console
---

<br>

-------

```{r}
# --- Setup
# Load packages
library(tidyverse)
library(here)
library(readxl)

# Settings
theme_set(theme_bw(base_size = 14))
theme_update(
  plot.title = element_text(face = "bold", hjust = 0.5),
  panel.grid.minor = element_blank(),
  panel.grid.major.x = element_blank()
)

# --- Define input files
# Metadata
meta1_file <- here("metadata/complete_list_Anchored_JP.xlsx")
meta2_file <- here("metadata/anchor_all_locations.csv")

# Other
missingness_file <- here("results/geno/consensus/stats/locus_filtering/per_sample_locus_missingness_filtered.tsv")
locus_length_file <- here("results/geno/consensus/stats/locus_lengths.tsv")
vcf_dir <- here("results/geno/consensus/stats/vcf")

# VCF depth
depth_files <- list.files(
  vcf_dir,
  full.names = TRUE,
  pattern = ".*_depth.tsv"
)

# VCF-derived files with counts of heterozygous, homozygous non-ref (alt),
# and homozygous reference (ref) sites per locus
het_files <- list.files(
  vcf_dir,
  full.names = TRUE,
  pattern = ".*_het_per-locus.txt"
)
alt_files <- list.files(
  vcf_dir,
  full.names = TRUE,
  pattern = ".*_hom-alt_per-locus.txt"
)
ref_files <- list.files(
  vcf_dir,
  full.names = TRUE,
  pattern = ".*_hom-ref_per-locus.txt"
)
```

```{r}
# --- Read and process the input files
# Sample metadata
meta1 <- read_excel(meta1_file) |>
  select(sample = code, species, locality, state, contam) |>
  mutate(species = sub("_", ". ", species))
meta2 <- read_csv(meta2_file, show_col_types = FALSE) |>
  select(sample = code, land_type = type)
meta <- left_join(meta1, meta2, by = "sample")

# Locus lengths
locus_lengths <- read_tsv(locus_length_file, col_types = "ci") |>
    rename(locus = locus_id) |>
    mutate(locus = sub(".*_(L[0-9]+)_.*", "\\1", locus))

# Missingness per sample
missingness <- read_tsv(missingness_file, col_types = "ccd") |>
    mutate(
        sample = sub(".*_FG_", "", sample),
        locus = sub("Bothrops_I9999_", "", locus)
    )

# Depth of coverage
depth <- read_tsv(depth_files, col_names = c("sample", "dp"), col_types = "cd") |>
    mutate(sample = sub(".*_FG_", "", sample))

# Heterozygous site counts
het <- read_tsv(
  het_files,
  col_select = 4:5,
  col_types = "ciici",
  col_names = c("chr", "start", "end", "locus", "n_het"),
  id = "sample"
) |>
  mutate(
    locus = sub("Bothrops_I9999_", "", locus),
    sample = sub(".*/.*FG_(.*)_het_per.*", "\\1", sample)
  )

# Homozygous non-ref (alt) site counts
alt <- read_tsv(
  alt_files,
  col_select = 4:5,
  col_types = "ciici",
  col_names = c("chr", "start", "end", "locus", "n_alt"),
  id = "sample"
) |>
  mutate(
    locus = sub("Bothrops_I9999_", "", locus),
    sample = sub(".*/.*FG_(.*)_hom-alt_per.*", "\\1", sample)
  )

# Homozygous reference (ref) site counts
ref <- read_tsv(
  ref_files,
  col_select = 4:5,
  col_types = "ciici",
  col_names = c("chr", "start", "end", "locus", "n_ref"),
  id = "sample"
) |>
  mutate(
    locus = sub("Bothrops_I9999_", "", locus),
    sample = sub(".*/.*FG_(.*)_hom-ref_per.*", "\\1", sample)
  )

# Combine
all_init <- full_join(het, alt, by = c("sample", "locus")) |>
  full_join(ref, by = c("sample", "locus")) |>
  mutate(
    sample = sub("P0021_FG_", "", sample),
    n_called = n_het + n_alt + n_ref
  ) |>
  left_join(locus_lengths, by = "locus")
```

## Check metadata

```{r}
meta |> count(land_type)
meta |> count(species)
meta |> count(state)


meta |> count(species, land_type)
meta |> count(species, state)
```

## Number of non-called loci

```{r}
# TODO: CHECK AND EXCLUDE LOCI WITH TOO FEW BASES CALLED
all_init |> filter(n_called == 0) |> count(sample) |> head()
all_init |> filter(n_called == 0) |> count(locus) |> head()
```

```{r}
# Remove sample-loci with fewer than 50 called bases
# and compute nr per 100 bp
all <- all_init |>
  filter(n_called > 50) |>
  select(!n_ref) |>
  mutate(n_diff = n_alt + (n_het / 2)) |>
  pivot_longer(
    cols = c(n_het, n_alt, n_diff),
    names_to = "genotype",
    values_to = "count"
  ) |>
  mutate(count = (count / n_called) * 100)

# Means by sample
all_smp <- all |>
  summarize(count = mean(count), .by = c("sample", "genotype")) |>
  left_join(meta, by = "sample") |>
  drop_na()

# Means by locus
all_loc <- all |> summarize(count = mean(count), .by = c("locus", "genotype"))
```

## Genotype count plots

### By species

```{r}
# Homozygous non-ref sites
all_smp |>
  filter(genotype == "n_alt") |>
  ggplot(aes(x = species, fill = species, y = count)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(
    width = 0.2,
    fill = "grey40",
    shape = 21,
    alpha = 0.5,
    size = 2.5
  ) +
  labs(
    title = "Homozygous non-ref sites",
    x = NULL,
    y = "Number of sites per 100 bp"
  ) +
  guides(fill = "none") +
  theme(axis.text.x = element_text(face = "italic"))

# Heterozygous sites
all_smp |>
  filter(type == "n_het") |>
  ggplot(aes(x = species, fill = species, y = count)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(
    width = 0.2,
    fill = "grey40",
    shape = 21,
    alpha = 0.5,
    size = 2.5
  ) +
  labs(
    title = "Heterozygous sites",
    x = NULL,
    y = "Number of sites per 100 bp"
  ) +
  guides(fill = "none") +
  theme(axis.text.x = element_text(face = "italic"))

# Total nr. of differences from the reference
all_smp |>
  filter(type == "n_diff") |>
  ggplot(aes(x = species, fill = species, y = count)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(
    width = 0.2,
    fill = "grey40",
    shape = 21,
    alpha = 0.5,
    size = 2.5
  ) +
  labs(
    title = "Total nr. of differences from the reference",
    x = NULL,
    y = "Number per 100 bp"
  ) +
  guides(fill = "none") +
  theme(axis.text.x = element_text(face = "italic"))
```

### *jararaca* mainland vs island

```{r}
# jararaca mainland vs island
all_smp |>
  filter(species == "jararaca", genotype != "n_diff") |>
  ggplot(aes(x = land_type, fill = land_type, y = count)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(
    width = 0.2,
    fill = "grey40",
    shape = 21,
    alpha = 0.5,
    size = 2.5
  ) +
  facet_wrap(vars(genotype)) +
  labs(
    title = "jararaca island vs. mainland",
    x = NULL,
    y = "Number of sites per 100 bp"
  ) +
  guides(fill = "none")

# jararaca by state
all_smp |>
  filter(species == "jararaca", genotype != "n_diff") |>
  ggplot(aes(x = state, fill = state, y = count)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(
    width = 0.2,
    fill = "grey40",
    shape = 21,
    alpha = 0.5,
    size = 2.5
  ) +
  facet_wrap(vars(genotype)) +
  labs(
    title = "jararaca island vs. mainland",
    x = NULL,
    y = "Number of sites per 100 bp"
  ) +
  guides(fill = "none")
```

### Contaminated vs. non-contaminated samples

```{r}
all_smp |> count(contam, species)
```


## Depth of coverage plots

```{r}
depth |>
  ggplot(aes(x = dp)) +
  geom_histogram(binwidth = 1, fill = "steelblue", color = "black") +
  labs(
    title = "Mean depth of coverage across all samples",
    x = "Mean depth of coverage",
    y = "Frequency"
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))
```

## Missingness (`N`) plots

```{r}
# By locus
missingness |>
    summarize(pct_N = mean(pct_N), .by = locus) |>
    ggplot(aes(x = pct_N)) +
    geom_histogram(binwidth = 1, fill = "steelblue", color = "black") +
    labs(
      title = "Mean missingness per locus",
      x = "Mean percentage of missing data (N)",
      y = "Frequency"
    ) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

# By sample
missingness |>
    summarize(pct_N = mean(pct_N), .by = sample) |>
    ggplot(aes(x = pct_N)) +
    geom_histogram(binwidth = 0.5, fill = "steelblue", color = "black") +
    labs(
      title = "Mean missingness per sample",
      x = "Mean percentage of missing data (N)",
      y = "Frequency"
    ) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1)))
```
